"""Auto-generated route registry for MoIP REST API v1.3.0."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Route:
    """HTTP route definition."""

    method: str
    path: str
    has_body: bool = False


ROUTES: tuple[Route, ...] = (
    Route("get", "/api/v1/base", False),
    Route("put", "/api/v1/base", True),
    Route("put", "/api/v1/base/auth/credentials", True),
    Route("get", "/api/v1/base/auth/login", False),
    Route("post", "/api/v1/base/auth/login", True),
    Route("get", "/api/v1/base/config", False),
    Route("put", "/api/v1/base/config", True),
    Route("post", "/api/v1/base/config/reset", True),
    Route("get", "/api/v1/base/firmware", False),
    Route("put", "/api/v1/base/firmware", True),
    Route("post", "/api/v1/base/hwcon/reboot", True),
    Route("get", "/api/v1/base/info", False),
    Route("get", "/api/v1/base/lan", False),
    Route("put", "/api/v1/base/lan", True),
    Route("get", "/api/v1/base/stats", False),
    Route("get", "/api/v1/base/time", False),
    Route("get", "/api/v1/moip/audio_rx/{id}", False),
    Route("post", "/api/v1/moip/audio_rx/{id}", True),
    Route("put", "/api/v1/moip/audio_rx/{id}", True),
    Route("get", "/api/v1/moip/audio_rx/{id}/channel/{channel}", False),
    Route("put", "/api/v1/moip/audio_rx/{id}/channel/{channel}", True),
    Route("get", "/api/v1/moip/audio_rx/{id}/channel/{channel}/bq", False),
    Route("get", "/api/v1/moip/audio_rx/{id}/channel/{channel}/bq/{bq}", False),
    Route("put", "/api/v1/moip/audio_rx/{id}/channel/{channel}/bq/{bq}", True),
    Route("get", "/api/v1/moip/audio_rx/{id}/main_bq/{bq}", False),
    Route("put", "/api/v1/moip/audio_rx/{id}/main_bq/{bq}", True),
    Route("get", "/api/v1/moip/audio_rx/{id}/sub_bq/{bq}", False),
    Route("put", "/api/v1/moip/audio_rx/{id}/sub_bq/{bq}", True),
    Route("get", "/api/v1/moip/audio_tx/{id}", False),
    Route("put", "/api/v1/moip/audio_tx/{id}", True),
    Route("get", "/api/v1/moip/change", False),
    Route("get", "/api/v1/moip/fixed_layout/{fixed_layout}", False),
    Route("get", "/api/v1/moip/group_rx", False),
    Route("get", "/api/v1/moip/group_rx/{id}", False),
    Route("put", "/api/v1/moip/group_rx/{id}", True),
    Route("get", "/api/v1/moip/group_tx", False),
    Route("get", "/api/v1/moip/group_tx/{id}", False),
    Route("put", "/api/v1/moip/group_tx/{id}", True),
    Route("get", "/api/v1/moip/ir_rx/{id}", False),
    Route("post", "/api/v1/moip/ir_rx/{id}", True),
    Route("put", "/api/v1/moip/ir_rx/{id}", True),
    Route("get", "/api/v1/moip/ir_tx/{id}", False),
    Route("put", "/api/v1/moip/ir_tx/{id}", True),
    Route("get", "/api/v1/moip/raw_change", False),
    Route("get", "/api/v1/moip/serial_rx/{id}", False),
    Route("post", "/api/v1/moip/serial_rx/{id}", True),
    Route("put", "/api/v1/moip/serial_rx/{id}", True),
    Route("delete", "/api/v1/moip/serial_rx/{id}/message", False),
    Route("get", "/api/v1/moip/serial_rx/{id}/message", False),
    Route("get", "/api/v1/moip/serial_tx/{id}", False),
    Route("post", "/api/v1/moip/serial_tx/{id}", True),
    Route("put", "/api/v1/moip/serial_tx/{id}", True),
    Route("delete", "/api/v1/moip/serial_tx/{id}/message", False),
    Route("get", "/api/v1/moip/serial_tx/{id}/message", False),
    Route("get", "/api/v1/moip/system", False),
    Route("post", "/api/v1/moip/system", True),
    Route("put", "/api/v1/moip/system", True),
    Route("get", "/api/v1/moip/system/status", False),
    Route("get", "/api/v1/moip/unit", False),
    Route("delete", "/api/v1/moip/unit/{id}", False),
    Route("get", "/api/v1/moip/unit/{id}", False),
    Route("post", "/api/v1/moip/unit/{id}", True),
    Route("put", "/api/v1/moip/unit/{id}", True),
    Route("delete", "/api/v1/moip/unit/{id}/log", False),
    Route("get", "/api/v1/moip/unit/{id}/log", False),
    Route("get", "/api/v1/moip/unit/{id}/stats", False),
    Route("get", "/api/v1/moip/usb_rx/{id}", False),
    Route("put", "/api/v1/moip/usb_rx/{id}", True),
    Route("get", "/api/v1/moip/usb_tx/{id}", False),
    Route("put", "/api/v1/moip/usb_tx/{id}", True),
    Route("get", "/api/v1/moip/video_rx/{id}", False),
    Route("post", "/api/v1/moip/video_rx/{id}", True),
    Route("put", "/api/v1/moip/video_rx/{id}", True),
    Route("get", "/api/v1/moip/video_rx/{id}/edid", False),
    Route("get", "/api/v1/moip/video_tx/{id}", False),
    Route("put", "/api/v1/moip/video_tx/{id}", True),
    Route("get", "/api/v1/moip/video_tx/{id}/edid", False),
    Route("get", "/api/v1/moip/video_tx/{id}/preview", False),
    Route("get", "/api/v1/moip/vidwall", False),
    Route("post", "/api/v1/moip/vidwall", True),
    Route("delete", "/api/v1/moip/vidwall/{id}", False),
    Route("get", "/api/v1/moip/vidwall/{id}", False),
    Route("put", "/api/v1/moip/vidwall/{id}", True),
)
